# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["web:5000"]
  - job_name: "mysql"
    static_configs:
      - targets: ["db:3306"]
